const dialogs = [
" Eat, drink and be scary!",
"Ghostly Greetings!",
"Halloween is a real treat",
"Have a fang-tastic night",
"Happy Haunting!",
"Have a bootiful Halloween",
"Don’t be a scaredy cat",
"I witch you a Happy Halloween",
"Stop in for a spell",
"Please park all brooms at the door",
"Caution! Witch Crossing",
"Boo to you from our crew",
"If you want a tasty sweet…",
"Be sure to holler trick or treat!",
"Knock! Knock!",
"Who’s there?",
"Vampires Drive Me Batty",
"Don’t Make Me Flip My Witch Switch",
"Zombies Love a Girl With Brains",
"If You’ve Got It, Haunt It",
"Witch Way to the Candy?",
"Ghouls Just Want to Have Fun",
"Join Our Coven",
"It’s All About the Candy",
  ];
  export default dialogs;
